In [8]:
import pandas as pd
mv=pd.read_csv("bollywood.csv")

In [9]:
mv.head(10)
mv.tail(99)

                                 movie              lead
1401  Shukriya: Till Death Do Us Apart       Anupam Kher
1402         Chalte Chalte (2003 film)    Shah Rukh Khan
1403     The Hero: Love Story of a Spy        Sunny Deol
1404               Baghban (2003 film)  Amitabh Bachchan
1405          Main Prem Ki Diwani Hoon    Hrithik Roshan
...                                ...               ...
1495            Hum Tumhare Hain Sanam    Shah Rukh Khan
1496               Aankhen (2002 film)  Amitabh Bachchan
1497                   Saathiya (film)      Vivek Oberoi
1498                    Company (film)        Ajay Devgn
1499              Awara Paagal Deewana      Akshay Kumar

[99 rows x 2 columns]

In [4]:
mv.sample

<bound method NDFrame.sample of                                      movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]>

In [5]:
mv.sample()

             movie          lead
50  Mission Mangal  Akshay Kumar

In [6]:
mv.value_counts()

movie                    lead
Gabbar Is Back           Akshay Kumar       2
Andaaz                   Akshay Kumar       2
Tanu Weds Manu: Returns  Kangana Ranaut     2
Yuvvraaj                 Salman Khan        1
Yuva                     Ajay Devgn         1
                                           ..
Yeh Mera India           Anupam Kher        1
Yeh Saali Aashiqui       Vardhan Puri       1
Youngistaan              Jackky Bhagnani    1
Yun Hota Toh Kya Hota    Paresh Rawal       1
Yakeen (2005 film)       Arjun Rampal       1
Name: count, Length: 1497, dtype: int64