In [2]:
import numpy as np
import pandas as pd

In [80]:
dl=pd.read_csv("deliveries.csv")
dl

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [79]:
mv=pd.read_csv("imdb-top-1000.csv")
mv

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [ ]:
mv.head(1)

In [ ]:
genres=mv.groupby("Genre")

In [ ]:
genres.sum()

In [ ]:
genres.min()

In [ ]:
genres.min()

In [ ]:
mv.groupby("Genre").sum()["Gross"].sort_values(ascending=False).head(3)

In [ ]:
#find the genrre with highest thwe imbd
mv.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending=False).head(1)

In [ ]:
#find the highst the direction on the basis of thw vote 

mv.groupby("Director")["No_of_Votes"].sum().sort_values(ascending=False).head(2)

In [ ]:
#hight rated imbd based
mv.groupby("IMDB_Rating")

In [ ]:
#highst no. of movies done by actor
mv.groupby("Star1")["Series_Title"].count().sort_values(ascending=False)

In [ ]:
genres.get_group("Horror")

In [ ]:
genres.get_group("Fantasy")

In [ ]:
genres.groups

In [ ]:
genres.describe()

In [ ]:
genres.nunique()

In [ ]:
genres.sum()

In [ ]:
genres.head(5)

In [ ]:
im

In [ ]:
genres.sum()

In [ ]:
#passing with dige

genres.agg(
    {
        "runtime":"mean",
        "IMDB_Rating":"mean"
        

    }
)

In [82]:
mv.agg(["max","min"])

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
max,Ôkami kodomo no Ame to Yuki,PG,321,Western,9.3,Ömer Faruk Sorak,Ömer Faruk Sorak,2343110,936662225.0,100.0
min,(500) Days of Summer,1920,45,Action,7.6,Aamir Khan,Aamir Khan,25088,1305.0,28.0

In [83]:
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [84]:
genres.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [87]:
#agg   passig with the dict
genres.agg(
    {
       "Runtime":"mean",
       "IMDB_Rating":"mean",
       "Gross":"mean",
       "No_of_Votes":"sum"
       

        
    }
)

              Runtime  IMDB_Rating         Gross  No_of_Votes
Genre
Action     129.046512     7.949419  1.897224e+08     72282412
Adventure  134.111111     7.937500  1.319017e+08     22576163
Animation   99.585366     7.930488  1.784326e+08     21978630
Biography  136.022727     7.938636  9.404952e+07     24006844
Comedy     112.129032     7.901290  1.010572e+08     27620327
Crime      126.392523     8.016822  7.899656e+07     33533615
Drama      124.737024     7.957439  1.225259e+08     61367304
Family     107.500000     7.800000  2.195553e+08       551221
Fantasy     85.000000     8.000000  3.913633e+08       146222
Film-Noir  104.000000     7.966667  4.197018e+07       367215
Horror     102.090909     7.909091  9.405902e+07      3742556
Mystery    119.083333     7.975000  1.047014e+08      4203004
Thriller   108.000000     7.800000  1.755074e+07        27733
Western    148.250000     8.350000  1.455538e+07      1289665

In [ ]:
genres.agg([min,max])
#passing with list

C:\Users\Sundram\AppData\Local\Temp\ipykernel_16276\107228508.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  genres.agg([min,max])
C:\Users\Sundram\AppData\Local\Temp\ipykernel_16276\107228508.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  genres.agg([min,max])

                              Series_Title  \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                               Released_Year       Runtime  \
                                           max           min   max     min
Genre
Action                                 Yôjinbô          1924  2019      45
Adventure                           Zombieland          1925    PG      88
Animation          Ôkami kodomo no Ame to Yuki          1940  2020      71
Biography                              Zerkalo          1928  2020      93
Comedy                Zindagi Na Milegi Dobara          1921  2020      68
Crime                        À bout de souffle          1931  2019      80
Drama                                Zwartboek          1925  2020      64
Family     Willy Wonka & the Chocolate Factory          1971  1982     100
Fantasy                              Nosferatu          1920  1922      76
Film-Noir                        The Third Man          1941  1949     100
Horror                               The Thing          1933  2017      71
Mystery                                Vertigo          1938  2012      96
Thriller                       Wait Until Dark          1967  1967     108
Western                 The Outlaw Josey Wales          1965  1976     132

               IMDB_Rating                    Director                    \
           max         min  max                    min               max
Genre
Action     321         7.6  9.0       Abhishek Chaubey       Zack Snyder
Adventure  228         7.6  8.6         Akira Kurosawa  Ömer Faruk Sorak
Animation  137         7.6  8.6            Adam Elliot   Yoshifumi Kondô
Biography  209         7.6  8.9             Adam McKay      Tom McCarthy
Comedy     188         7.6  8.6  Alejandro G. Iñárritu       Zoya Akhtar
Crime      229         7.6  9.2         Akira Kurosawa      Yavuz Turgul
Drama      242         7.6  9.3             Aamir Khan       Çagan Irmak
Family     115         7.8  7.8             Mel Stuart  Steven Spielberg
Fantasy     94         7.9  8.1            F.W. Murnau      Robert Wiene
Film-Noir  108         7.8  8.1       Alfred Hitchcock       John Huston
Horror     122         7.6  8.5     Alejandro Amenábar  William Friedkin
Mystery    138         7.6  8.4            Alex Proyas     Terry Gilliam
Thriller   108         7.8  7.8          Terence Young     Terence Young
Western    165         7.8  8.8         Clint Eastwood      Sergio Leone

                              Star1                   No_of_Votes           \
                                min               max         min      max
Genre
Action                   Aamir Khan      Yun-Fat Chow       25312  2303232
Adventure                Aamir Khan      Yves Montand       29999  1512360
Animation             Adrian Molina      Yôji Matsuda       25229   999790
Biography              Adrien Brody     Éric Toledano       27254  1213505
Comedy                   Aamir Khan  Ömer Faruk Sorak       26337   939631
Crime                    Ajay Devgn    Vincent Cassel       27712  1826188
Drama                    Abhay Deol    Çetin Tekindor       25088  2343110
Family                  Gene Wilder      Henry Thomas      178731   372490
Fantasy                 Max Schreck     Werner Krauss       57428    88794
Film-Noir           Humphrey Bogart     Teresa Wright       59556   158731
Horror              Anthony Perkins  Sigourney Weaver       27007   787806
Mystery    Bernard-Pierre Donnadieu       Vidya Balan       33982  1129894
Thriller             Audrey Hepburn    Audrey Hepburn       27733    27733
Western              Clint Eastwood       Henry Fonda       65659   688390

                 Gross              Metascore
                   min          max       min    max
Genre
Action          3296.0  936662225.0      33.0   98.0
Adventure      61001.0  874211619.0      41.0  100.0
Animation     128985.0  873839108.0      61.0   96.0
Biography      21877.0  753585104.0      48.0   97.0
Comedy          1305.0  886752933.0      45.0   99.0
Crime           6013.0  790482117.0      47.0  100.0
Drama           3600.0  924558264.0      28.0  100.0
Family       4000000.0  435110554.0      67.0   91.0
Fantasy    337574718.0  445151978.0       NaN    NaN
Film-Noir     449191.0  123353292.0      94.0   97.0
Horror         89029.0  298791505.0      46.0   97.0
Mystery      1035953.0  474203697.0      52.0  100.0
Thriller    17550741.0   17550741.0      81.0   81.0
Western      5321508.0   31800000.0      69.0   90.0

In [91]:
genres.agg(
    {
        "Runtime":["max","min","sum"],
        "No_of_Votes":"max",
        "Metascore":"min"
        
        
        

    }
)

          Runtime             No_of_Votes Metascore
              max  min    sum         max       min
Genre
Action        321   45  22196     2303232      33.0
Adventure     228   88   9656     1512360      41.0
Animation     137   71   8166      999790      61.0
Biography     209   93  11970     1213505      48.0
Comedy        188   68  17380      939631      45.0
Crime         229   80  13524     1826188      47.0
Drama         242   64  36049     2343110      28.0
Family        115  100    215      372490      67.0
Fantasy        94   76    170       88794       NaN
Film-Noir     108  100    312      158731      94.0
Horror        122   71   1123      787806      46.0
Mystery       138   96   1429     1129894      52.0
Thriller      108  108    108       27733      81.0
Western       165  132    593      688390      69.0

In [4]:
pl=pd.read_csv("deliveries.csv")
pl

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [11]:
pl.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [22]:
six=pl[pl["batsman_runs"]==6]

six.groupby("batsman")["batsman"].count().sort_values(ascending=False).head(5)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
Name: batsman, dtype: int64