In [1]:
import numpy as np
import pandas as pd

In [5]:
dl= pd.read_csv("deliveries.csv")
dl.head(5)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [15]:
#top 10 batsman run

dl.groupby("batsman")["batsman_runs"].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [31]:
#total no. of 6

six=dl[dl["batsman_runs"]==6]
six.groupby("batsman")["batsman_runs"].count().sort_values(ascending=False).head(3)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
Name: batsman_runs, dtype: int64

In [53]:
#find batsamn who last 5 over me jaada 4 aur 6 lagaya hai

lst=dl[dl["over"]>15]
temp=lst[(lst["batsman_runs"]==4) | (lst["batsman_runs"]==6)]
temp.groupby("batsman")["batsman"].count().sort_values(ascending=False)

batsman
MS Dhoni          340
RG Sharma         208
AB de Villiers    208
KA Pollard        206
V Kohli           160
                 ...
AR Bawne            1
TS Mills            1
TA Boult            1
T Taibu             1
T Curran            1
Name: batsman, Length: 360, dtype: int64

In [65]:
#vk runs against all team

vk=dl[dl["batsman"]=="V Kohli"]
vk.groupby("bowling_team")["batsman_runs"].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [72]:
#create function to give highest score of batsman

dl[dl["batsman"]=="V Kohli"]

dl.groupby("match_id")["batsman"]